[metadata]
name = matrace
version = 0.1.0
description = MATLAB-to-Python interpreter and compiler
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
python_requires = >=3.10

[options]
packages = find:
include_package_data = True

[options.packages.find]
exclude =
    tests*

[tool:pytest]
testpaths = tests